# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MVPXCTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVPXCTest
  pod "Alamofire"
  pod 'Sourcery'
  pod 'CocoaDebug', :configurations => ['Debug']


  target 'MVPXCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVPXCTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
